### ISSUE TITLE
您好，能分享下关于facenet训练部分的代码？

### ISSUE THREAD

**Issue by Gabriel-18** [fanyihua0309/Low-FaceNet#4]

**Comment by fanyihua0309** [comment]
FaceNet训练请见https://github.com/bubbliiiing/facenet-pytorch

**Comment by Gabriel-18** [comment]
有个疑问facenet训练的时候应该用低光CASIA-WebFace还是正常光的CASIA-WebFace。或者训练两次，分别用低光和高光。

**Comment by d1c2s3** [comment]
我有个疑问，在做消融实验室去掉face_loss损失时，得到的图片是红色的，求告知怎么解决
